namespace IndustrialPark
{
    public enum AssetTemplate
    {
        Null,
        UserTemplate,

        // Controllers
        Counter,
        Conditional,
        Dispatcher,
        Group,
        Portal,
        Script,
        SoundGroup,
        Text,
        Timer,
        CamTweak,
        DuplicatotronSettings,

        // BFBB Pickups and Tikis
        Shiny_Red,
        Shiny_Yellow,
        Shiny_Green,
        Shiny_Blue,
        Shiny_Purple,
        Underwear,
        Spatula,
        Sock,
        Spongeball,
        Golden_Underwear,
        Smelly_Sundae,
        WoodenTiki,
        FloatingTiki,
        ThunderTiki,
        ShhhTiki,
        StoneTiki,
        Artwork,
        SteeringWheel,
        PowerCrystal,

        // TSSM Pickups and Tikis
        Manliness_Red,
        Manliness_Yellow,
        Manliness_Green,
        Manliness_Blue,
        Manliness_Purple,
        KrabbyPatty,
        GoofyGooberToken,
        TreasureChest,
        Nitro,
        Wood_Crate,
        Hover_Crate,
        Explode_Crate,
        Shrink_Crate,
        Steel_Crate,

        // BFBB Enemies
        Fodder,
        Hammer,
        TarTar,
        ChompBot,
        GLove,
        Chuck,
        Chuck_Trigger,
        Monsoon,
        Monsoon_Trigger,
        Sleepytime,
        Sleepytime_Moving,
        BombBot,
        Arf,
        Tubelet,
        BzztBot,
        Slick,
        Slick_Trigger,
        Jellyfish_Pink,
        Jellyfish_Blue,
        Duplicatotron,

        // ...but not for user
        ArfDog,
        TubeletSlave,

        // TSSM Enemies
        Jelly_Critter,
        Jelly_Bucket,
        Fogger_GoofyGoober,
        Fogger_Desert,
        Fogger_ThugTug,
        Fogger_Trench,
        Fogger_Junkyard,
        Fogger_Planktopolis,
        Fogger_v1,
        Fogger_v2,
        Fogger_v3,
        Slammer_GoofyGoober,
        Slammer_Desert,
        Slammer_ThugTug,
        Flinger_Desert,
        Flinger_Trench,
        Flinger_Junkyard,
        Spinner_ThugTug,
        Spinner_Junkyard,
        Spinner_Planktopolis,
        Popper_Trench,
        Popper_Planktopolis,
        Minimerv,
        Mervyn,
        Turret_v1,
        Turret_v2,
        Turret_v3,

        // Stage Items
        Button_Red,
        PressurePlate,
        TaxiStand,
        TexasHitch,
        TexasHitch_PLAT,
        Checkpoint,
        Checkpoint_Invisible,
        BusStop,
        TeleportBox,
        ThrowFruit,
        FreezyFruit,
        Springboard,
        HoveringPlatform,
        BungeeHook,
        BungeeDrop,

        // TSSM
        Swinger,
        Swinger_PLAT,
        Ring,
        RingControl,

        // ...but not for user
        PressurePlateBase,
        BusStop_DYNA,
        BusStop_BusSimp,
        BusStop_Camera,
        BusStop_Lights,
        BusStop_Trigger,
        ThrowFruitBase,
        Checkpoint_Timer,
        Checkpoint_Talkbox,
        Checkpoint_SIMP,
        BungeeHook_SIMP,

        // Placeable
        Camera,
        Marker,
        Box_Trigger,
        Sphere_Trigger,
        Cylinder_Trigger,
        Point_MVPT,
        Area_MVPT,
        Dyna_Pointer,
        Boulder_Generic,
        Button_Generic,
        Destructible_Generic,
        ElectricArc_Generic,
        Hangable_Generic,
        NPC_Generic,
        Pendulum_Generic,
        Platform_Generic,
        Player_Generic,
        SIMP_Generic,
        VIL_Generic,
        UI_Generic,
        UIFT_Generic,
        SFX_OnEvent,
        SFX_OnRadius,
        SDFX,
        LightEmitter_Generic,

        // Other
        AnimationList,
        CollisionTable,
        Environment,
        Flythrough,
        JawData,
        LevelOfDetailTable,
        MaterialMap,
        PipeInfoTable,
        ShadowTable,
        SoundInfo,
        EmptyBSP,

        PasteClipboard
    }
}
