namespace IndustrialPark
{
    public enum AssetTemplate
    {
        Null,
        UserTemplate,

        // Controllers
        Group,
        Counter,
        Conditional,
        Dispatcher,
        Portal,
        Text,
        Timer,
        DuplicatotronSettings,

        // Pickups and Tikis
        Shiny_Red,
        Shiny_Yellow,
        Shiny_Green,
        Shiny_Blue,
        Shiny_Purple,
        Underwear,
        Spatula,
        Sock,
        Spongeball,
        Golden_Underwear,
        Smelly_Sundae,
        WoodenTiki,
        FloatingTiki,
        ThunderTiki,
        ShhhTiki,
        StoneTiki,
        Artwork,
        SteeringWheel,
        PowerCrystal,

        // Enemies
        Fodder,
        Hammer,
        TarTar,
        ChompBot,
        GLove,
        Chuck,
        Chuck_Trigger,
        Monsoon,
        Monsoon_Trigger,
        Sleepytime,
        Sleepytime_Moving,
        BombBot,
        Arf,
        Tubelet,
        BzztBot,
        Slick,
        Slick_Trigger,
        Jellyfish_Pink,
        Jellyfish_Blue,
        Duplicatotron,

        // ...but not for user
        ArfDog,
        TubeletSlave,

        // Stage Items
        Button_Red,
        PressurePlate,
        TaxiStand,
        TexasHitch,
        TexasHitch_PLAT,
        Checkpoint,
        Checkpoint_Invisible,
        BusStop,
        TeleportBox,
        ThrowFruit,
        FreezyFruit,
        Springboard,
        HoveringPlatform,
        BungeeHook,
        BungeeDrop,

        // ...but not for user
        PressurePlateBase,
        BusStop_DYNA,
        BusStop_BusSimp,
        BusStop_Camera,
        BusStop_Lights,
        BusStop_Trigger,
        ThrowFruitBase,
        Checkpoint_Timer,
        Checkpoint_Talkbox,
        Checkpoint_SIMP,
        BungeeHook_SIMP,

        // Placeable
        Marker,
        SphereTrigger,
        PointMVPT,
        EnemyAreaMVPT,
        Boulder_Generic,
        Button_Generic,
        Camera,
        Destructible_Generic,
        ElectricArc_Generic,
        Platform_Generic,
        Player_Generic,
        SIMP_Generic,
        VIL_Generic,

        // Other
        AnimationList,
        CollisionTable,
        Environment,
        JawData,
        LevelOfDetailTable,
        MaterialMap,
        PipeInfoTable,
        ShadowTable,
        SoundInfo,
    }
}
